Teams/urls.py
from django.urls import path
from . import views
from .views import GroupCreateView, GroupTaskCreateView, GroupListView, GroupTaskDetailView, GroupTaskUpdateView, GroupTaskDeleteView, GroupListViewAll

#this list defines the extentions to any url starting with /group/...
urlpatterns = [
    #path('', views.groupTest, name='group-test'), #/group/
    path('', GroupListView.as_view(), name='group-test'),
    path('all/', GroupListViewAll.as_view(), name='group-test-all'),
    path('join/', views.join_group, name='group-join'), #/group/join/
    path('create/', GroupCreateView.as_view(), name='group-create' ), #/group/create
    path('create_task/', GroupTaskCreateView.as_view(), name='team-task-create'),
    path('task/<int:pk>/',GroupTaskDetailView.as_view(), name='team-task-detail'),
    path('task/<int:pk>/update/',GroupTaskUpdateView.as_view(), name='team-task-update'),
    path('task/<int:pk>/delete/',GroupTaskDeleteView.as_view(), name='team-task-delete'),

]

spm/urls.py
from django.contrib import admin
from django.contrib.auth import views as SignIn_views
from django.urls import path, include
from Users import views as userCreate_view

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', userCreate_view.register, name='Create_account'),
    path('login/', SignIn_views.LoginView.as_view(template_name='Users/login.html'), name='login'),
    path('logout/', SignIn_views.LogoutView.as_view(template_name='Users/logout.html'), name='logout'),
    path('chore/', include('chores.urls')),
    path('group/', include('Teams.urls')),
    path('', include('Users.urls')),

]

Teams/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse

'''This defines the team table.'''
class Team(models.Model):
    team_name = models.CharField(max_length=100, unique=True)
    team_pswd = models.CharField(max_length=15)

    def __str__(self):
        return self.team_name


class Team_Chore(models.Model):
    team_chore_name = models.CharField(max_length=100, verbose_name='Group Task Name')
    content = models.TextField(verbose_name='Task Content')
    date_created = models.DateField(auto_now_add=True)
    date_due = models.DateField(verbose_name='Due Date')
    is_complete = models.BooleanField(default=False)
    creator = models.ForeignKey(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.team_chore_name

    def get_absolute_url(self):
        return reverse('team-task-detail', kwargs={'pk' : self.pk})

Users/models.py
from django.db import models
from django.contrib.auth.models import User
from Teams.models import Team

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    team = models.ForeignKey(Team, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
       return f'{self.user.username}'

Teams/forms.py
from django import forms

'''This file contains all of the forms for the group app'''

'''This class defines the fields for the JoinGroup form'''
class JoinGroup(forms.Form):
    name = forms.CharField(label='Team Name', max_length=100)
    pswd = forms.CharField(label='Team Password', max_length=15)




Teams/views.py
'''imports'''
from pyexpat import model
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from .models import Team, Team_Chore
from .forms import JoinGroup
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.http import HttpResponse
import csv
from Users.models import Profile

'''defines the my group webpage'''
# @login_required
# def groupTest(request):
#     #team of the current user
#     current_user = request.user.profile.team

#     #a dictionary containing all of the other team members
#     context = {'members' : User.objects.filter(profile__team = current_user).values_list('username', flat=True)}

#     #returns a rendering of the html doc for the page, passes the group memebrs as arguments
#     return render(request, 'Teams/GroupTest.html', context)


class GroupListView(LoginRequiredMixin, ListView):
    model = Team_Chore
    template_name ='Teams/GroupTest.html'
    context_object_name = 'GroupTasks'

    def get_queryset(self, *args, **kwargs):
        qs = Team_Chore.objects.filter(team = self.request.user.profile.team, is_complete = False).order_by('is_complete', 'date_due')
        return qs

class GroupListViewAll(LoginRequiredMixin, ListView):
    model = Team_Chore
    template_name ='Teams/GroupTestAll.html'
    context_object_name = 'GroupTasks'

    def get_queryset(self, *args, **kwargs):
        qs = Team_Chore.objects.filter(team = self.request.user.profile.team).order_by('is_complete', 'date_due')
        return qs


'''defines the join group page'''
@login_required
def join_group(request):

    #if the a post request is made ...
    if request.method == 'POST':
        #creates an instance of the JoinGroup form
        form = JoinGroup(request.POST)

        #if the form has vaild values
        if form.is_valid():

            #if the user is not already in a group
            if request.user.profile.team == None:

                #if the inputed team name and password match an existing group
                if Team.objects.filter(team_name=form.cleaned_data['name']).filter(team_pswd = form.cleaned_data['pswd']).exists():
                    #add the cooresponding group as a foreign key to the user
                    request.user.profile.team = Team.objects.filter(team_name=form.cleaned_data['name']).filter(team_pswd = form.cleaned_data['pswd']).first()
                    #save the update to the user's profile
                    request.user.profile.save()
                    #redirect to the group page
                    return HttpResponseRedirect('/group/')
                else:
                    #if the team name and password do not match an existing group
                    messages.warning(request, 'No Such Group')
            #if the user is already in a group
            else:
                messages.warning(request, 'You are already in a Group')
    
    #if any other type of request is made .. do nothing basically
    else:
      form = JoinGroup()

    #render the html doc for the page, passing the form object as an argument
    return render(request, 'Teams/JoinGroup.html', {'form': form})        



'''class based definition of the create group webpage'''
'''to do add user passes test for not in group'''
class GroupCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    #createView is a django included view to create a form to fill in a table
    #this view creates a new row in the Team (group) table

    #html doc for this view
    template_name = 'Teams/CreateTeam.html'
    #the model (db table) that this createview care about
    model = Team
    #the fields that the created form should use
    fields = ['team_name', 'team_pswd']
    #on successful creation, the user is redirected to the join group page
    success_url = reverse_lazy('group-join')

    def test_func(self):
        has_group = self.request.user.profile.team
        if has_group:
            return False
        else:
            return True



class GroupTaskCreateView(LoginRequiredMixin, CreateView):

    template_name = 'Teams/CreateGroupTask.html'
    model = Team_Chore
    fields = ['team_chore_name', 'content', 'date_due']

    def form_valid(self, form):

        form.instance.creator = self.request.user
        form.instance.team = self.request.user.profile.team
        return super().form_valid(form)

    success_url = reverse_lazy('group-test')

class GroupTaskDetailView(LoginRequiredMixin, UserPassesTestMixin, DetailView):
    template_name = 'Teams/DetailGroupTask.html'
    model = Team_Chore

    def post(self, *args, **kwargs):
        response = HttpResponse(
            content_type='text/csv',
            headers={'Content-Disposition': 'attachment; filename="event.csv"'},
        )
        name = list(Team_Chore.objects.filter(**kwargs).values_list('team_chore_name', flat=True))
        date = list(Team_Chore.objects.filter(**kwargs).values_list('date_due', flat=True))
        description = list(Team_Chore.objects.filter(**kwargs).values_list('content', flat=True))

        writer = csv.writer(response)
        writer.writerow(['Subject', 'Start Date', 'End Date', 'Description'])
        writer.writerow([str(name[0]), str(date[0]), str(date[0]), str(description[0])])

        return response

    def test_func(self):
        task = self.get_object()
        if self.request.user.profile.team == task.team:
            return True
        return False

class GroupTaskUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'Teams/UpdateGroupTask.html'
    model = Team_Chore
    fields = ['team_chore_name', 'content', 'date_due', 'is_complete']
    success_url = reverse_lazy('group-test')

    def test_func(self):
        task = self.get_object()
        if self.request.user.profile.team == task.team:
            return True
        return False

class GroupTaskDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    template_name = 'Teams/DeleteGroupTask.html'
    model = Team_Chore
    success_url = reverse_lazy('group-test')

    def test_func(self):
        task = self.get_object()
        if self.request.user.profile.team == task.team:
            return True
        return False
    

Teams/templates/Teams/CreateGroupTask.html
{% extends "Teams/TeamBase.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
              {% csrf_token %}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4">Create an new task for your group</legend>
                  {{ form|crispy }}
              </fieldset>
              <div class ="form-group">
                <button class="btn btn-outline-success" type="submit">Create</button>
              </div>

        </form>
    </div>
{% endblock content %}

Teams/templates/Teams/CreateTeam.html
{% extends "chores/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
              {% csrf_token %}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4">Create an new Group</legend>
                  {{ form|crispy }}
              </fieldset>
              <div class ="form-group">
                <button class="btn btn-outline-success" type="submit">Create</button>
              </div>

        </form>
    </div>
{% endblock content %}

Teams/templates/Teams/DeleteGroupTask.html
{% extends "Teams/TeamBase.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
              {% csrf_token %}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4">Delete This Task Forever?</legend>
                  <h1>Are you sure you want to delete: "{{object.team_chore_name}}"?</h1>
                  <p>This will delete the task for your whole group</p>
              </fieldset>
              <div class ="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Burn it with Fire</button>
                <a class="btn btn-outline-secondary" href="{% url 'chore-detail' object.id %}" >No, I want to keep it</a>
              </div>

        </form>
    </div>
{% endblock content %}

Teams/templates/Teams/DetailGroupTask.html
{% extends "Teams/TeamBase.html" %}
{% block content %} 

    <article class="media content-section">
        <div class="media-body">
        <div class="article-metadata">
            <small class="text-muted">Created By: {{ object.creator }} on {{ object.date_created }} &emsp;</small>
            <small class="text-muted">Due: {{ object.date_due }} &emsp;</small>
            {% if object.is_complete == True %}
            <small class="text-muted"><span style="color: darkgreen">Complete: YES</span></small>
            {% else %}
            <small class="text-muted"><span style="color: crimson">Complete: NO</span></small>
            {% endif %}
            
        </div>
        <h2 class="article-title">{{ object.team_chore_name }}</h2>
        <p class="article-content">{{ object.content }}</p>
        {% if object.team == user.profile.team %}
            <a class="btn btn-info btn-sm mt-2 mb-2" href="{% url 'team-task-update' object.id %}">Edit</a>
            <a class="btn btn-danger btn-sm mt-2 mb-2" href="{% url 'team-task-delete' object.id %}">Delete</a>
            <form action="" method="post">
                {% csrf_token %}
                <button class="btn btn-info btn-sm mt-2 mb-2" name="button" value="Export">Export</button>
            </form>
        {% endif %}
        </div>
    </article>

{% endblock content %}

Teams/templates/Teams/GroupTest.html
{% extends "Teams/TeamBase.html" %}
{% block drop %} 


  <div class="btn-toolbar col-md-8">
    <div class="dropdown">
      <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="toggleview" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Incomplete Tasks
      </button>
      <div class="dropdown-menu" aria-labelledby="toggleview">
        <a class="dropdown-item" href="{% url 'group-test' %}">Incomplete Tasks</a>
        <a class="dropdown-item" href="{% url 'group-test-all' %}">All Tasks</a>
      </div>
    </div>
      <div>
        <a class="btn btn-info btn-sm mx-2" href="{% url 'team-task-create' %}">Create New Task</a>
      </div>
  </div>
  <p></p>
{% endblock drop %}

{% block content %} 

  {% for GroupTask in GroupTasks %}

        <article class="media content-section">
            <div class="media-body">
            <div class="article-metadata">
                <small class="text-muted">Created By: {{ GroupTask.creator }} on {{ GroupTask.date_created }} &emsp;</small>
                <small class="text-muted">Due: {{ GroupTask.date_due }} &emsp;</small>
                {% if GroupTask.is_complete == True %}
                <small class="text-muted"><span style="color: darkgreen">Complete: YES</span></small>
                {% else %}
                <small class="text-muted"><span style="color: crimson">Complete: NO</span></small>
                {% endif %}
                
            </div>
            <h2><a class="article-title" href="{% url 'team-task-detail' GroupTask.id %}">{{ GroupTask.team_chore_name }}</a></h2>
            <p class="article-content">{{ GroupTask.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}
{% block sidebar %}
<div class="col-md-4">
  <div class="content-section">
    <h3>Team Members</h3>
    <p class='text-muted'>
      <ul class="list-group">
        {% for member in GroupTasks.first.creator.profile.team.profile_set.all %}
        <li class="list-group-item list-group-item-light">{{member}}</li>
        {% endfor %}
      </ul>
    </p>
  </div>
  {% endblock sidebar %}

Teams/templates/Teams/GroupTestAll.html
{% extends "Teams/TeamBase.html" %}
{% block drop %} 


  <div class="btn-toolbar col-md-8">
    <div class="dropdown">
      <button class="btn btn-primary btn-sm dropdown-toggle" type="button" id="toggleview" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        All Tasks
      </button>
      <div class="dropdown-menu" aria-labelledby="toggleview">
        <a class="dropdown-item" href="{% url 'group-test' %}">Incomplete Tasks</a>
        <a class="dropdown-item" href="{% url 'group-test-all' %}">All Tasks</a>
      </div>
    </div>
      <div>
        <a class="btn btn-info btn-sm mx-2" href="{% url 'team-task-create' %}">Create New Task</a>
      </div>
  </div>
  <p></p>
{% endblock drop %}

{% block content %} 

  {% for GroupTask in GroupTasks %}

        <article class="media content-section">
            <div class="media-body">
            <div class="article-metadata">
                <small class="text-muted">Created By: {{ GroupTask.creator }} on {{ GroupTask.date_created }} &emsp;</small>
                <small class="text-muted">Due: {{ GroupTask.date_due }} &emsp;</small>
                {% if GroupTask.is_complete == True %}
                <small class="text-muted"><span style="color: darkgreen">Complete: YES</span></small>
                {% else %}
                <small class="text-muted"><span style="color: crimson">Complete: NO</span></small>
                {% endif %}
                
            </div>
            <h2><a class="article-title" href="{% url 'team-task-detail' GroupTask.id %}">{{ GroupTask.team_chore_name }}</a></h2>
            <p class="article-content">{{ GroupTask.content }}</p>
            </div>
        </article>
    {% endfor %}
{% endblock content %}
{% block sidebar %}
<div class="col-md-4">
  <div class="content-section">
    <h3>Team Members</h3>
    <p class='text-muted'>
      <ul class="list-group">
        {% for member in GroupTasks.first.creator.profile.team.profile_set.all %}
        <li class="list-group-item list-group-item-light">{{member}}</li>
        {% endfor %}
      </ul>
    </p>
  </div>
  {% endblock sidebar %}

Teams/templates/Teams/JoinGroup.html
{% extends "chores/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
              {% csrf_token %}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4">Join an Existing Group</legend>
                  {{ form|crispy }}
              </fieldset>
              <div class ="form-group">
                <button class="btn btn-outline-success" type="submit">Join!</button>
              </div>

        </form>
        <div class="border-top pt-4">
            <small class="text-muted">Need to create a group? <a class="ml-2" href="{% url 'group-create' %}">Create Group</a> </small>
        </div>
    </div>
{% endblock content %}

Teams/templates/Teams/TeamBase.html
{% load static %}

<!DOCTYPE html>
<html>
<head>
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
 
     <!-- Bootstrap CSS -->
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

     <link rel="stylesheet" type="text/css" href="{% static 'chores/main.css' %}">
    <title>SoftProjectManager</title>   
</head>
<body>
    <header class="site-header">
        <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
          <div class="container">
            <a class="navbar-brand mr-4" href="/">SoftProjectManager</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
              <div class="navbar-nav mr-auto">
                <a class="nav-item nav-link" href="{% url 'chore-home' %}">My Chores</a>
                {% if user.profile.team %}
                <a class="nav-item nav-link" href="{% url 'group-test' %}">My Group</a>
                {% else %}
                <a class="nav-item nav-link" href="{% url 'group-join' %}">Join Group</a>
                <a class="nav-item nav-link" href="{% url 'group-create' %}">Create Group</a>
                {% endif %}
              </div>
              <div class="navbar-nav">
                {% if user.is_authenticated %}
                  <a class="nav-item nav-link" href="{% url 'team-task-create' %}">New Task for Team</a>
                  <a class="nav-item nav-link" href="{% url 'logout' %}">Logout</a>
                {% else %}
                  <a class="nav-item nav-link" href="{% url 'login' %}">Login</a>
                  <a class="nav-item nav-link" href="{% url 'Create_account' %}">Register</a>
                {% endif %}
              </div>
            </div>
          </div>
        </nav>
    </header>
    <main role="main" class="container">
        <div class="row vertical-middle">
          <div class="col-md-8">
            {% if messages %}
              {% for message in messages %}
                <div class="alert alert-{{ message.tags }}">
                  {{ message }}
                </div>
              {% endfor %}
            {% endif %}
            <h1>{{user.profile.team}}</h1>
            {% block drop %}{% endblock drop %}
            {% block content %}{% endblock content %}
          </div>
          {% block sidebar %}{% endblock sidebar %}
        </div>
    </main>
    <footer class="class fixed-bottom">
      <p class = "para">Authors & Contact info</p>
      <ul class="contact">
        <li><a href="mailto:hege@example.com" class = "foottext">Richard Frost</a></li>
        <li><a href="mailto:hege@example.com"class = "foottext">Alyssa Christoff</a></li>
        <li><a href="mailto:hege@example.com" class = "foottext">Zachery Fahley</a></li>
        <li><a href="mailto:hege@example.com" class = "foottext">Jonathon Esbri</a></li>
        <li><a href="mailto:hege@example.com" class = "foottext">Kyle Do</a></li>
      </ul>
  </footer>
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

</body>
</html>

Teams/templates/Teams/UpdateGroupTask.html
{% extends "Teams/TeamBase.html" %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="content-section">
        <form method="POST">
              {% csrf_token %}
              <fieldset class="form-group">
                  <legend class="border-bottom mb-4">Update Group Task</legend>
                  {{ form|crispy }}
              </fieldset>
              <div class ="form-group">
                <button class="btn btn-outline-success" type="submit">Update</button>
              </div>

        </form>
    </div>
{% endblock content %}